### ISSUE TITLE
The name of this repo needs work

### ISSUE THREAD

**Issue by Lnaden** [choderalab/cookiecutter-compchem#1]
As the title says

**Comment by Lnaden** [comment]
Suggested names by @jchodera `compchem-cookiecutter` or `cookiecutter-compchem` (later keeps in line with other [cookiecutter packages](https://github.com/audreyr/cookiecutter)

**Comment by dgasmith** [comment]
`compchem-cookiecutter` would be good with me.

**Comment by Lnaden** [comment]
Is anyone opposed to the `cookiecutter-compchem` since that seems to be the accepted naming convention on the main cookiecutter site?

**Comment by Lnaden** [comment]
I have renamed this repo to `cookiecutter-compchem`

All of the old links should still work, but please use the new one. 

If you have cloned this, make sure to set the `git` remote url
```bash
git remote set-url origin git@github.com:choderalab/cookiecutter-compchem
```
syntax is a bit different with `https`
