### ISSUE TITLE
Substitute author names in LICENSE

### ISSUE THREAD

**Issue by jchodera** [choderalab/cookiecutter-compchem#14]
Currently, the [LICENSE](https://github.com/choderalab/cookiecutter-compchem/blob/master/LICENSE#L3) includes a fixed set of author names for copyright. This can be auto-populated via cookiecutter.

**Comment by Lnaden** [comment]
That LICENSE file is actually for the Cookiecutter as a whole. The [generated LICENSE file](https://github.com/choderalab/cookiecutter-compchem/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/LICENSE) will 
[fill](https://github.com/choderalab/cookiecutter-compchem/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/LICENSE#L4) [in](https://github.com/choderalab/cookiecutter-compchem/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/LICENSE#L24) the name as provided. The exception is the LGPL one which has a hard coded pointer to the Free Software Foundation as part of its license.

**Comment by Lnaden** [comment]
Which license it attaches is also chosen when you generate the template based on user choice, defaulting to MIT

**Comment by jchodera** [comment]
Thanks!
