### ISSUE TITLE
Dependency source choices

### ISSUE THREAD

**Issue by dgasmith** [choderalab/cookiecutter-compchem#17]
During the setup users are greeted with the following option:

```
Select dependency_source:
1 - conda-forge
2 - conda
3 - pip
Choose from 1, 2, 3 [1]:
```

Users may become slightly confused if they need to pull from both conda and pip for example (or if they dont know where they need to pull from). Can this either be reworded or become a multiple choice selection?

**Comment by Lnaden** [comment]
This is not the best option, I agree. Right now this only configures the CI choices as to where to prefer packages from. One problem is `codecov` on only on `pip` and `conda-forge`, but not on Anaconda `default` channel, so if the `conda` option is chosen, it uses `conda` then `pip`

One of the limitations of the `cookiecutter.json` file is that option is limited to just `"dependency_source": ["conda-forge", "conda", "pip"]` and its filled in from there.

**Comment by jchodera** [comment]
`conda` means just the default `anaconda` channel, right? If so, maybe `anaconda` would be a bit clearer?
