### ISSUE TITLE
Badges!

### ISSUE THREAD

**Issue by jchodera** [choderalab/cookiecutter-compchem#19]
Since the cookiecutter sets up `.travis.yml` and codecov, it would be cool if it added the badges to the top of `README.md`, which will also serve as a reminder to enable those services to get the badges to work.

**Comment by ctk3b** [comment]
Moar badges ™️ 

![image](https://user-images.githubusercontent.com/3527431/37694767-e9205c20-2c86-11e8-8b48-67eed9d7bbc5.png)

(but yes I completely agree with this suggestion)

**Comment by dgasmith** [comment]
Good to add docs and appveyor badges as well.

On that note it might be wise to have a switch for Windows CI or not with appveyor.

**Comment by Lnaden** [comment]
I had considered having a "Do you want CI on these OS's" as part of the setup, but I wanted to keep the options minimal, and users can always delete the corresponding files. But if you want to have the options, we can include them!

**Comment by jchodera** [comment]
I think a single option for whether windows CI support (appveyor.yaml and the corresponding badge) should be included is reasonable.

**Comment by Lnaden** [comment]
What about for OSX?

**Comment by jchodera** [comment]
I think we can assume we want to use Travis-CI for `linux` and `osx` by default.
