### ISSUE TITLE
Update recommended pytest entrypoint to pytest

### ISSUE THREAD

**Issue by malramsay64** [choderalab/cookiecutter-compchem#43]
`pytest` is the recommended method of invoking the tests in the pytest library, see [relevant issue](https://github.com/pytest-dev/pytest/issues/1629#issue-161422224). All the pytest [documentation](https://docs.pytest.org/en/latest/usage.html) uses `pytest` over `py.test`.

As a template for starting a project I don't see backwards compatibility as a problem, although this came into effect with [pytest 3.0 released August 2016](https://github.com/pytest-dev/pytest/releases/tag/3.0.0).

**Comment by dgasmith** [comment]
Closed by #44.
